# Generated by Django 4.2.1 on 2023-07-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0002_customuser_is_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_pro',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deactivateAcct',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
