# Generated by Django 4.2.1 on 2023-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0003_remove_customuser_is_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_deactivateAcct',
            field=models.BooleanField(default=False),
        ),
    ]
