# Generated by Django 4.2.1 on 2023-08-20 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0005_remove_customuser_is_deactivateacct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('closing_bal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction_log_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital_billing_app.transactionlog')),
            ],
        ),
    ]
