# Generated by Django 4.2.1 on 2023-08-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0006_accounthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounthistory',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='accounthistory',
            old_name='transaction_log_id',
            new_name='transaction_log',
        ),
        migrations.RenameField(
            model_name='transactionlog',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transactionlog',
            old_name='subscription_id',
            new_name='subscription',
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='status',
            field=models.CharField(blank=True, default='fail', max_length=200, null=True),
        ),
    ]
