# Generated by Django 4.2.1 on 2023-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0008_alter_accounthistory_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='debit',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='service_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='service_provided',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
