# Generated by Django 4.2.1 on 2023-08-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0009_remove_customuser_balance_remove_customuser_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='closing_bal',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='credit',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='debit',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
