# Generated by Django 4.2.1 on 2023-08-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0010_alter_accounthistory_closing_bal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authorize_all_trans',
            field=models.BooleanField(default=True),
        ),
    ]
