# Generated by Django 4.2.1 on 2023-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0013_accounthistory_created_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_lock_inactive_mode',
            field=models.BooleanField(default=True),
        ),
    ]
