# Generated by Django 4.2.1 on 2023-10-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0014_customuser_is_lock_inactive_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='', max_length=200, unique=True)),
                ('street_address1', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=200)),
                ('postal', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('phone2', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_agreement', models.TextField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='unique_referral_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
