# Generated by Django 4.2.1 on 2023-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0015_companyinfo_customuser_unique_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='bonus_percent',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_referral_bonus_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ur_referred_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
