# Generated by Django 4.2.1 on 2023-10-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0017_accounthistory_payaccount_accounthistory_paycard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounthistory',
            old_name='payAccount',
            new_name='bank',
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='refPay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
