# Generated by Django 4.2.1 on 2023-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0019_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_referral_process_complete',
            field=models.BooleanField(default=False),
        ),
    ]
