# Generated by Django 4.2.1 on 2023-11-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_billing_app', '0020_referral_is_referral_process_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubscription',
            name='period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
